<?xml version="1.0" standalone="yes"?>
<!DOCTYPE student [
    <!ELEMENT student (name, address, age , email)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>

<student>
    <name>Subash Danuwar</name>
    <address> Pepsicola, Townplanning </address>
    <age>22</age>
    <email>suwasdanuwar18@gmail.com</email>
</student>